### ISSUE TITLE
License checks still exists for Visual Studio 2022 extension

### ISSUE THREAD

**Issue by michaelmsonne** [ironmansoftware/powershell-pro-tools#66]
As per.: https://blog.ironmansoftware.com/powershell-pro-tools-end-of-life/

This will getting to be Open-Source - but when you install the extension for Visual Studio 2022 it still showing this:
![image](https://github.com/ironmansoftware/powershell-pro-tools/assets/49366751/90e1ec1c-af6e-4b11-89a2-44d31e003242)

This is installed from the Marketplace from the link over here: https://github.com/ironmansoftware/powershell-pro-tools

V. 2024.3.0

**Comment by adamdriscoll** [comment]
The Visual Studio extension open source release is still in progress: #45

**Comment by michaelmsonne** [comment]
Roger @adamdriscoll - looking forward to that 😃
