### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by n04x** [ironmansoftware/powershell-pro-tools#74]
This error occurs on the latest version of VS Code:
Version: 1.91.1 (user setup)
OS: Windows 11
PowerShell Pro Tools version: v2024.7.3 (latest)

I have been trying to open the ps1 file by clicking the button "Open with PSScriptPad" and I get the following errors:
```
Exception running command: $OpenPsScriptPad System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
```

Also, I get this: Extension ironmansoftware.powershellprotools has provided an invalid tree item.

I have tried to open the xaml file and it asks me the following: Open a PS1 file to edit with the form designer before running this command.

I am not sure what is happening there and I do not understand the cause... I've been trying to navigate through the Issues and so far I've been unsucessful.

**Comment by n04x** [comment]
I have also tried a new folder with new ps1 file, launch it in vscode and yet still get the same error

**Comment by adamdriscoll** [comment]
This has been resolved in our main branch but has not been released. The Open with PSScriptPad command has been removed because it is not a part of this repository. PSScriptPad is still available on our website for download without the license restriction.
