### ISSUE TITLE
still starting

### ISSUE THREAD

**Issue by germanlagomarsino** [ironmansoftware/powershell-pro-tools#79]
Good morning, Since the extension is free I can't use it in VScode, it always gives me the same error.

![image](https://github.com/user-attachments/assets/94358eaf-5f17-46bb-8cf2-d177615a6f66)

**Comment by adamdriscoll** [comment]
@germanlagomarsino Do you have the persistent terminal sessions setting enabled? 

https://code.visualstudio.com/docs/terminal/advanced#_persistent-sessions

I would also look in the output page for PowerShell Pro Tools for logging information.

**Comment by germanlagomarsino** [comment]
Disabling persistent sessions solved the problem. thank you so much!

**Comment by adamdriscoll** [comment]
Great! I added an error and option to disable it in 2024.7.5. I think others have been running into this as well. 

https://github.com/ironmansoftware/powershell-pro-tools/releases/tag/vscode-2024.7.5
