### ISSUE TITLE
Issues running scripts in Visual Studio

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-pro-tools#82]
I haven't actually had the time to look into this yet but this was reported on the Marketplace site: 

```
Ps1 files that run fine under PowerShell 6/7 (normal and ISE) immediately generate errors here. I tried the PowerShell Module and PowerShell script projects and neither worked. When you open one file (File1) and try and run it (it fails). Then you load a different file and try and run it and this extension continues to execute File1 -- even if you delete file1 from the project or system. Even the sample files generated by the new project wizard don't run. Well, the wizard continues to run File1 so I don't really know if their sample files work or not.
```

**Comment by adamdriscoll** [comment]
Not sure if related: https://forums.ironmansoftware.com/t/visual-studio-2022-no-variables-showing-in-debug/11038

**Comment by pdeg** [comment]
Curses.  I got that too.  The cannot view or watch variables in the debugger.  Assumed I had borked my Visual Studio install.. 
 So I uninstalled Visual Studio and installed the latest rev.. Went to reinstall the pro tools extension and now I have 2 problems.

Yes, I know.  I really need to get up to speed with gitub.  I went install the pro tools from the ironman web site, and found
out that it was being open sourced here.  No probs.  .  BUT there is no downloader for visual studio at https://ironmansoftware.com/powershell-pro-tools/downloads.  So I came here?  And I, for the life of me, cannot 
work out how to get hold of the latest rev.  Do you want me to create an installer ?

Forgive me .. but my first concern is to get my really rubbish bit of powershell working.   I use the excellent
forms stuff.  Do not want to get distracted with sorting out on installer or  migrating to VS Code et al.. at this stage.

Please help.

**Comment by pdeg** [comment]
Sorry ... to be more specific ..  Can't get forms, but can run the existing .ps1

This when I do a quickwatch. ...............   Hover gives me nothing.

Unable to evaluate the expression. Operation not supported. Unknown error: 0x80070057.

**Comment by selflessFlash** [comment]
Rolled back to VS enterprise 17.8.13 and still debugging issues.

**Comment by pdeg** [comment]
Go back to a previous version of pro tools

P

**Comment by selflessFlash** [comment]
Thank you for the update sir. 
Cheers!
