### ISSUE TITLE
Debugging Issue - hover over variable, no tooltip with value

### ISSUE THREAD

**Issue by jbyte2009** [ironmansoftware/powershell-pro-tools#84]
When running the debugger and looking at variables by hovering them reveals no tool tip of value of variable.  I tried to Add Watch or Quick Watch and no values show.

![PowerShellIssue](https://github.com/user-attachments/assets/bceb3708-ec33-4e0e-b795-039635ac055d)

**Comment by selflessFlash** [comment]
Same with me. I may also say that the locals window is empty during debugging but filled when debugging C# code.

Microsoft Visual Studio Enterprise 2022
Version 17.11.2
VisualStudio.17.Release/17.11.2+35222.181
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA332
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.11.230.51983
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.11.230.51983
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.11.230.51983
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.11.0-3.24376.4+5e3a11e2e7f952da93f9d35bd63a2fa181c0608b
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Entity Framework Core Power Tools   2.6
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu.

GitHub Copilot   0.2.1634.3922
GitHub Copilot is an AI pair programmer that helps you write code faster and with less work.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.11.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

PowerShell Pro Tools for Visual Studio   1.0
A set of tools for developing and debugging PowerShell scripts and modules in Visual Studio.

Progress Telerik UI for ASP.NET Core Extension   2024.3.808.150
Progress® Telerik® UI for ASP.NET Core Extension

Progress Telerik UI for ASP.NET MVC Extension   2024.3.808.150
Progress® Telerik® UI for ASP.NET MVC Extension

Razor (ASP.NET Core)   17.11.3.2442001+68650a7d94261bc56a1f4bc522c2ee35314b1abb
Provides languages services for ASP.NET Core Razor.

SlowCheetah - XML config transforms   1.0
This package enables you to transform your app.config or any other XML file based on the build configuration. It also adds additional tooling to help you create XML transforms.

SQL Server Data Tools   17.11.38.0
Microsoft SQL Server Data Tools

SQL Server Reporting Services   16.0.20583.0
Microsoft SQL Server Reporting Services Designers 
Version 16.0.20583.0

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.30715.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.11.0-3.24376.4+5e3a11e2e7f952da93f9d35bd63a2fa181c0608b
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.11.0-beta.24317.3+c07c8ebad62f6629b36349381991a299598a8d74
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

**Comment by selflessFlash** [comment]
Rolled back to VS enterprise 17.8.13 and still debugging issues.
