### ISSUE TITLE
PowerShell Pro Tools requires the Microsoft PowerShell or PowerShell Preview extension.

### ISSUE THREAD

**Issue by mwoffenden** [ironmansoftware/powershell-pro-tools#93]
This suddenly started popping up in the lower right while using VS Code.  Why?

![2024-11-09_12-01-17](https://github.com/user-attachments/assets/3478bca8-485c-48d2-98e0-d30a27deab6d)

**Comment by adamdriscoll** [comment]
Do you have either of these extensions installed and active?

**Comment by mwoffenden** [comment]
Yes, PowerShell Pro Tools.  What should we do?

**Comment by adamdriscoll** [comment]
You need to have one of the Microsoft extensions installed as well. PowerShell Pro Tools just augments the Microsoft extension. 

https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell

**Comment by mwoffenden** [comment]
Is this a new requirement?  I've not seen messages like this before.

**Comment by adamdriscoll** [comment]
No. This has always been a requirement.
